external_apps/crm/urls.py
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------
# $Id: urls.py 425 2009-07-14 03:43:01Z tobias $
# ----------------------------------------------------------------------------
#
#    Copyright (C) 2008-2009 Caktus Consulting Group, LLC
#
#    This file is part of django-crm and was originally extracted from minibooks.
#
#    django-crm is published under a BSD-style license.
#    
#    You should have received a copy of the BSD License along with django-crm.  
#    If not, see <http://www.opensource.org/licenses/bsd-license.php>.
#

from django.conf.urls.defaults import *
from django.contrib.auth import views as auth_views

import crm.views as views

urlpatterns = patterns('',
    
    url(r'^dashboard/$', views.dashboard, name='crm_dashboard'),
    
    url(r'^search/$', views.quick_search, name='quick_search'),
    
    url(r'^interaction/$', views.list_interactions, name='list_interactions'),
    url(r'^(?:person/(?P<person_id>\d+)/)?interaction/create/$', views.create_edit_interaction, name='create_interaction'),
    url(r'^interaction/(?P<interaction_id>\d+)/edit/$', views.create_edit_interaction, name='edit_interaction'),
    url(r'^interaction/(?P<interaction_id>\d+)/remove/$', views.remove_interaction, name='remove_interaction'),
    
    url(r'^person/list/$', views.list_people, name='list_people'),
    url(r'^person/create/$', views.create_edit_person, name='create_person'),
    url(r'^person/register/$', views.register_person, name='register_person'),
    url(r'^person/(?P<person_id>\d+)/$', views.view_person, name='view_person'),
    url(r'^person/(?P<person_id>\d+)/edit/$', views.create_edit_person, name='edit_person'),
    
    url(
        r'^contact/(?P<contact_slug>[-\w]+)/email/$',
        views.email_contact,
        name='email_contact',
    ),
    
    # businesses
    url(r'^business/list/$', views.list_businesses, name='list_businesses'),
    url(
        r'^business/(?P<business_id>\d+)/$',
        views.view_business,
        name='view_business',
    ),
    url(
        r'^business/create/$',
        views.create_edit_business,
        name='create_business',
    ),
    url(
        r'^business/(?P<business_id>\d+)/edit/$',
        views.create_edit_business,
        name='edit_business',
    ),
    url(
        r'^business/(?P<business_id>\d+)/contact/(?P<user_id>\d+)/edit/$',
        views.edit_business_relationship,
        name='edit_business_relationship',
    ),
    
    # projects
    url(
        r'^business/(?P<business_id>\d+)/(?:project/(?P<project_id>\d+)/)?(?:contact/(?P<user_id>\w+)/)?(?P<action>remove|add)/$',
        views.associate_contact,
        name='associate_contact',
    ),
    
    url(r'^book/(?P<file_name>[\w.]+)$', views.address_book, name='address_book'),
    
    url(
        r'^registration/activate/(?P<activation_key>\w+)/$',
        views.activate_login,
        name='activate_login',
    ),
    url(
        r'^registration/contact/$',
        views.create_registration,
        name='create_registration',
    )
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from crm.xmlrpc import rpc_handler

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # crm and contactinfo URLs (required)
    (r'^crm/', include('crm.urls')),
    (r'^contactinfo/', include('contactinfo.urls')),
    (r'^ajax/', include('ajax_select.urls')),
    
    url(r'^xml-rpc/', rpc_handler, name='xml_rpc'),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    
    # use the contrib.auth login/logout views for authentication (optional)
    url(
        r'^accounts/login/$', 'django.contrib.auth.views.login', 
        name='auth_login',
    ),
    url(
        r'^accounts/logout/$', 'django.contrib.auth.views.logout', 
        name='auth_logout',
    ),
    # redirect '/' to the CRM dashboard (optional)
    url(
        '^$', 
        'django.views.generic.simple.redirect_to', 
        {'url': '/crm/dashboard/'},
    ),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        ( r'^%s(?P<path>.*)' % settings.MEDIA_URL.lstrip('/'),
          'django.views.static.serve',
          { 'document_root' : settings.MEDIA_ROOT, 'show_indexes': True }
        ),
    )

external_apps/crm/models.py
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------
# $Id: models.py 425 2009-07-14 03:43:01Z tobias $
# ----------------------------------------------------------------------------
#
#    Copyright (C) 2008-2009 Caktus Consulting Group, LLC
#
#    This file is part of django-crm and was originally extracted from minibooks.
#
#    django-crm is published under a BSD-style license.
#    
#    You should have received a copy of the BSD License along with django-crm.  
#    If not, see <http://www.opensource.org/licenses/bsd-license.php>.
#
import datetime

from django.db import models
from django.contrib.auth.models import User, Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.contrib.localflavor.us import models as us_models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.utils.functional import curry
from django.template.loader import render_to_string
from django.template.defaultfilters import slugify
from django.core.mail import send_mail

from crm import managers as crm_managers

from contactinfo import models as contactinfo

DEFAULT_ACCOUNT_ACTIVATION_DAYS = 15

CONTACT_TYPES = (
    ('individual', 'Individual'),
    ('business', 'Business'),
)

def slugify_uniquely(s, queryset=None, field='slug'):
    """
    Returns a slug based on 's' that is unique for all instances of the given
    field in the given queryset.
    
    If no string is given or the given string contains no slugify-able
    characters, default to the given field name + N where N is the number of
    default slugs already in the database.
    """
    new_slug = new_slug_base = slugify(s)
    if queryset:
        queryset = queryset.filter(**{'%s__startswith' % field: new_slug_base})
        similar_slugs = [value[0] for value in queryset.values_list(field)]
        i = 1
        while new_slug in similar_slugs:
            new_slug = "%s%d" % (new_slug_base, i)
            i += 1
    return new_slug


class Contact(models.Model):
    user = models.ForeignKey(
        User,
        null=True,
        blank=True,
        unique=True,
        related_name='contacts',
    )
    business_types = models.ManyToManyField(
        'BusinessType',
        related_name='businesses',
        blank=True,
    )
    
    # related_names ending in '+' will be ignored/hidden by Django
    contacts = models.ManyToManyField(
        'self',
        through='ContactRelationship',
        symmetrical=False,
        related_name='related_contacts+',
    )
    locations = models.ManyToManyField(contactinfo.Location, blank=True)
    
    type = models.CharField(max_length=32, choices=CONTACT_TYPES)
    name = models.CharField(max_length=255, blank=True)
    first_name = models.CharField(max_length=50, blank=True)
    middle_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    sort_name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    email = models.EmailField(blank=True)
    description = models.TextField(blank=True)
    notes = models.TextField(blank=True)
    picture = models.ImageField(null=True, blank=True, max_length=1048576, upload_to="picture/profile/")
    external_id = models.CharField(max_length=32, blank=True)
    
    objects = models.Manager()
    
    def get_full_name(self):
        return "%s %s" % (self.first_name, self.last_name)
    
    def add_accessor_methods(self, *args, **kwargs):
        for contact_type, name in CONTACT_TYPES:
            setattr(
                self,
                '%s_relations' % contact_type,
                curry(self._get_TYPE_relations, contact_type=contact_type)
            )
    
    def is_editable_by(self, user):
        has_membership = False
        try:
            from members.models import Membership
            has_membership = (
                Membership.objects.filter(contact=self).count() > 0
                and self.user == user
            )
        except ImportError:
            pass
        has_perms = user.has_perms((
            'crm.add_contact',
            'crm.change_contact',
        ))
        return (has_membership or has_perms)
    
    def _get_TYPE_relations(self, contact_type):
        return self.contacts.filter(type=contact_type)
    
    def __init__(self, *args, **kwargs):
        super(Contact, self).__init__(*args, **kwargs)
        self.add_accessor_methods()
    
    def _get_exchange_types(self):
        # import here to avoid circular import
        try:
            from minibooks.ledger.models import ExchangeType
            return ExchangeType.objects.filter(
                business_types__businesses=self
            )
        except ImportError:
            return []
    exchange_types = property(_get_exchange_types)
    
    def primary_phone(self):
        for type in ('office', 'mobile', 'home'):
            for location in self.user.locations.all():
                for phone in location.phones.all():
                    if phone.type == type:
                        return phone
        
        return None
    
    def as_text_block(self):
        fields = []
        if self.type == 'individual':
            fields = [
                'First Name: %s\n' % self.first_name,
                'Middle Name: %s\n' % self.middle_name,
                'Last Name: %s\n' % self.last_name,
                'Email: %s\n' % self.email,
            ]
            for location in self.locations.order_by('id'):
                for phone in location.phones.order_by('id'):
                    fields.append('%s Phone: %s\n' % (location.type, phone))
                for address in location.addresses.order_by('id'):
                    fields.append('%s Address: %s\n' % (
                        location.type,
                        unicode(address).replace("\n", " ")
                    ))
        return fields
    
    class Meta:
        permissions = (
            ("access_xmlrpc", "Can access minibooks XML-RPC service"),
            ("view_profile", "Can view contacts"),
            ("view_business", "Can view businesses"),
        )
    
    def __unicode__(self):
        if self.name:
            name = self.name
        else:
            name = "%s %s" % (self.first_name, self.last_name)
        return name


class ContactRelationship(models.Model):
    types = models.ManyToManyField(
        'RelationshipType',
        related_name='contact_relationships',
        blank=True,
    )
    from_contact = models.ForeignKey('Contact', related_name='from_contacts')
    to_contact = models.ForeignKey('Contact', related_name='to_contacts')

    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    
    class Meta:
        unique_together = ('from_contact', 'to_contact')
        
    def save(self, *args, **kwargs):
        create_mirror = kwargs.pop('create_mirror', True)
        super(ContactRelationship, self).save(*args, **kwargs)
        if create_mirror:
            mirror, created = ContactRelationship.objects.get_or_create(
                from_contact=self.to_contact,
                to_contact=self.from_contact,
            )
            mirror.types = self.types.all()
            mirror.start_date = self.start_date
            mirror.end_date = self.end_date
            mirror.save(create_mirror=False)

    def __unicode__(self):
        return "%s's relationship to %s" % (
            self.from_contact,
            self.to_contact,
        )


class BusinessType(models.Model):
    name = models.CharField(max_length=255)
    can_view_all_projects = models.BooleanField(
        default=False,
        help_text='Allow billable expenses to projects not associated with a business of this type.  For example, a billable expense for staying at a hotel, but will be billed to a client project.  When creating an exchange, this value specifies whether or not all projects show up under the Project drop down menu.'
    )
    
    def __unicode__(self):
        return self.name


class RelationshipType(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.CharField(max_length=255, unique=True, editable=False)
    
    def save(self):
        queryset = RelationshipType.objects.all()
        if self.id:
            queryset = queryset.exclude(id__exact=self.id)
        self.slug = slugify_uniquely(self.name, queryset, 'slug')
        super(RelationshipType, self).save()
    
    def __unicode__(self):
        return self.name


class Interaction(models.Model):
    """ Communication log """
    
    INTERACTION_TYPES = (
        ('email', 'Email'),
        ('meeting', 'Meeting'),
        ('phone', 'Phone'),
        ('business', 'Business'),
        ('exchange', 'Exchange'),
    )

    date = models.DateTimeField()
    type = models.CharField(max_length=15, choices=INTERACTION_TYPES)
    completed = models.BooleanField(default=False)
    memo = models.TextField(blank=True)
    cdr_id = models.TextField(null=True)
    
    contacts = models.ManyToManyField(Contact, related_name='interactions')
    
    def src(self):
        if self.cdr:
            return self.cdr.src
    src.short_description = 'Source'

    def dst(self):
        if self.cdr:
            return self.cdr.dst
    dst.short_description = 'Destination'

    def duration(self):
        if self.cdr:
            time = self.cdr.duration / 60.0
            return "%.2f minutes" % time
    duration.short_description = 'Duration'
    
    class Meta:
        ordering = ['-date']
        permissions = (
            ('view_interaction', 'Can view interaction'),
            ('view_todo_list', 'Can view to do list'),
        )
    
    def __unicode__(self):
        return "%s: %s" % ( self.date.strftime("%m/%d/%y"), self.type )

external_apps/crm/templates/crm/person/create_edit.html
{% extends "crm/person/view.html" %}

{% block title %}{% if contact %}Update {{ contact }}{% else %}Add new person{% endif %}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    {% load breadcrumb_tags %}
    {% if contact %}
        {% add_crumb 'Edit' %}
    {% else %}
        {% add_crumb 'Create' %}
    {% endif %}
{% endblock %}

{% block javascript %}
{{ location_form.media }}
{% endblock %}

{% block css %}
<link charset='UTF-8' rel='stylesheet' type='text/css' media='screen' href='{{ MEDIA_URL }}css/django-contactinfo.css' />
{% endblock %}

{% block content %}

<h2>{% if contact %}Update {{ contact }}{% else %}Add new person{% endif %}</h2>

<form id='create-edit-person' accept-charset='UTF-8' method='post' action=''>
    {% csrf_token %}
	<table class='vertical'>
		{% for form in forms %}
			{{ form }}
		{% endfor %}
        {% include 'contactinfo/_create_edit_location.html' %}
		<tr>
			<td>&nbsp;</td>
			<td class='submit'>
				<input type='button' value='Cancel' onclick='history.go(-1)' />
				&nbsp;
				<input type='submit' name='submit' value='{% if contact %}Update{% else %}Create{% endif %} &rarr;' />
			</td>
		</tr>
	</table>
</form>

{% endblock %}

external_apps/crm/templates/crm/person/list.html
{% extends "base.html" %}

{% block title %}People{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    {% load breadcrumb_tags %}
    {% add_crumb 'People' 'list_people' %}
{% endblock %}

{% block content %}
<h2>People</h2>
{% if perms.crm %}
	<ul class='header-actions-left'>
	{% if perms.auth.add_user %}
		<li><a href='{% url create_person %}'>Create Person</a></li>
	{% endif %}
	</ul>
{% endif %}

<form class='search' accept-charset='UTF-8' method='get' action=''>
	<ul>
		{{ form.as_ul }}
		<li class='form-buttons'>
			<input class='large-button' type='submit' name='submit' value='Search &rarr;' />
		</li>
	</ul>
</form>

{% load pagination_tags %}
{% autopaginate people %}

{% paginate %}
<table class='people'>
	<tr>
		<th>Name</th>
		<th>E-mail</th>
		<th>Phone Number(s)</th>
		<th>Notes</th>
	</tr>
	{% for person in people %}
	<tr>
		<td class='name'><a href='{% url view_person person_id=person.id %}'>{{ person.get_full_name }}</a></td>
		<td><a href='mailto:{{ person.email }}'>{{ person.email }}</a></td>
		<td class='phone'>
    {% for location in person.locations.all %}
        {% for phone in location.phones.all %}
			<a href='sip://1-{{ phone }}'>{{ phone }}</a> ({{ phone.type }})<br />
		{% endfor %}
    {% endfor %}
		</td>
		<td>{{ person.notes }}</td>
	</tr>
	{% endfor %}
</table>
{% paginate %}

{% endblock %}

external_apps/crm/templates/crm/person/register.html
{% extends "base.html" %}

{% block title %}New Account Registration{% endblock %}

{% block content %}

<h2>New Account Registration</h2>

<p>To register for a new account, fill out the form below and click Go.  Your password will be emailed to you (and we won't use your email for any other purpose).</p>

<form id='register-person' accept-charset='UTF-8' method='post' action=''>
    {% csrf_token %}
	<table class='vertical'>
		{{ form }}
		<tr>
			<td>&nbsp;</td>
			<td class='submit'>
				<input type='button' value='Cancel' onclick='history.go(-1)' />
				&nbsp;
				<input type='submit' name='submit' value='Go &rarr;' />
			</td>
		</tr>
	</table>
</form>

{% endblock %}

external_apps/crm/templates/crm/person/view.html
{% extends "crm/person/list.html" %}
{% load markup %}

{% block breadcrumb %}
    {{ block.super }}
    {% load breadcrumb_tags %}
    {% if contact %}
        {% add_crumb contact 'view_person' contact.pk %}
    {% endif %}
{% endblock %}

{% block title %}{{ contact }}{% endblock %}

{% block content %}
<h2>{{ contact }}</h2>
<ul class='header-actions-left'>
{% if can_edit %}
	<li><a href='{% url edit_person person_id=contact.id %}?next={% url view_person person_id=contact.id %}'>Edit Person</a></li>
{% endif %}
</ul>

<table class='vertical' id='person-profile'>
{% if contact.email %}
    <tr>
        <th>Email:</th>
        <td><a href='mailto:{{ contact.email }}'>{{ contact.email }}</a> (<a href='{% url email_contact contact.slug %}'>Send Email)</a></td>
    </tr>
{% endif %}
{% for location in contact.locations.all %}
    {% for address in location.addresses.all %}
        <tr>
            <th>{{ location.type|capfirst }} Address:</th>
            <td>{{ address }}</td>
        </tr>
    {% endfor %}

    {% for phone in location.phones.all %}
        <tr>
            <th>{{ location.type|capfirst }} {{ phone.type|capfirst }}:</th>
            <td><a href='sip://1-{{ phone }}'>{{ phone }}</a></td>
        </tr>
    {% endfor %}
{% endfor %}
{% if contact.notes %}
    <tr>
        <th>Notes:</th>
        <td>{{ contact.notes|textile }}</td>
    </tr>
{% endif %}
</table>

{% if perms.crm.view_profile %}
    {% ifnotequal contact.business_relations.count 0 %}
        <h3>Businesses</h3>
        <ul class='businesses person'>
        {% for business in contact.business_relations.select_related %}
            <li><a href='{% url view_business business_id=business.id %}'>{{ business.name }}</a></li>
        {% endfor %}
        </ul>
    {% endifnotequal %}
{% endif %}

{% if perms.crm.view_interaction %}
    <h3>Recent Interactions</h3>
    <ul class='header-actions-left'>
    {% if perms.crm.add_interaction %}
    	<li><a href='{% url create_interaction person_id=contact.id %}?next={{ request.path }}'>New Interaction</a></li>
    {% endif %}
    </ul>
    {% include 'crm/interaction/_list.html' %}
{% endif %}

<br style='clear: both;' />
{% endblock %}